### ISSUE TITLE
Increase points for passing static analysis in pub.dev

### ISSUE THREAD

**Issue by PackRuble** [PackRuble/weather_animation#13]
Now in pub.dev:
```

Pass static analysis      30/50
Found 29 issues. Showing the first 2:
- WARNING: The annotation 'JsonSerializable' can only be used on classes.
- WARNING: The annotation 'ignoreJson' can only be used on fields or getters.
```

The answer is probably here:
rrousselGit/freezed#897

**Comment by lishaduck** [comment]
That issue is about names, and was fixed about a year ago.
That is an interesting error though. File a new issue with Freezed?

**Comment by PackRuble** [comment]
I was preparing tasks to implement a new version of the package and therefore pinned this task since it was open at that moment. So it's mostly a reminder for me and a place to look for solutions if things go wrong. With a high probability, everything should be fine.

**Comment by PackRuble** [comment]
Adding a line 
```
// ignore_for_file: invalid_annotation_target
```
to the model file helped improve the specs.
