### ISSUE TITLE
Assertion failed: container.dart:265:15 decoration != null || clipBehavior == Clip.none is not true

### ISSUE THREAD

**Issue by imckh** [PackRuble/weather_animation#15]
https://github.com/PackRuble/weather_animation/blob/1350e8cbf0ab99aae48012b1724826fe2683bf2b/lib/src/wrapper_scene_widget.dart#L689

```log
======== Exception caught by widgets library =======================================================
The following assertion was thrown building WrapperScene(dirty):
Assertion failed: file:///opt/homebrew/Caskroom/flutter/3.24.3/flutter/packages/flutter/lib/src/widgets/container.dart:265:15
decoration != null || clipBehavior == Clip.none
is not true

The relevant error-causing widget was: 
  WrapperScene WrapperScene:file:///Users/ckh/.pub-cache/hosted/pub.dev/weather_animation-1.1.0/lib/src/model/scenes.dart:65:42
When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 296:3  throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3   assertFailed
packages/flutter/src/widgets/container.dart 265:58                           new
packages/weather_animation/src/wrapper_scene_widget.dart 687:12              build
```

**Comment by PackRuble** [comment]
Could you please provide minimal code to reproduce the problem

**Comment by imckh** [comment]
> Could you please provide minimal code to reproduce the problem

- Flutter version 3.24.3
- Dart version 3.5.3

main.dart
```dart
import 'package:flutter/material.dart';

import 'package:flutter_test_project/weather/all_weathers_scenes.dart';

void main() {
  runApp(ExampleApp());
}
```

all_weathers_scenes.dart
> Copied from 
https://github.com/PackRuble/weather_animation/blob/1350e8cbf0ab99aae48012b1724826fe2683bf2b/example/example.dart
```
// Copy this code into your project and run

import 'package:flutter/gestures.dart' show PointerDeviceKind;
import 'package:flutter/material.dart';
import 'package:weather_animation/weather_animation.dart';

class ExampleApp extends StatelessWidget {
  const ExampleApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Weather animation package - example',
      // debugShowCheckedModeBanner: false,
      home: HomePage(),
    );
  }
}

class HomePage extends StatelessWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    // ERROR!
    // return WeatherScene.sunset.sceneWidget;
    
    // SAME ERROR!
    return Scaffold(
      body: ScrollConfiguration(
        behavior: ScrollConfiguration.of(context).copyWith(
          dragDevices: {
            PointerDeviceKind.touch,
            PointerDeviceKind.mouse,
          },
        ),
        child: PageView(
          children: [for (final w in WeatherScene.values) w.sceneWidget],
        ),
      ),
    );
  }
}
```

**Comment by eunbeek** [comment]
Hello @imckh 
I have a same issue, but I solved it like below. I think decoration, clip are requried with WrapperScene Widget but something is missing in the library. So If you want to handle this error temporary until @PackRuble fix it, try it. 

```
  @override
  Widget build(BuildContext context) {
    return WrapperScene.weather(
      scene: WeatherScene.sunset,
      decoration: const BoxDecoration(),
      clip: Clip.hardEdge,
    );
  }
```

**Comment by PackRuble** [comment]
Thanks to @imckh and @eunbeek for participating in this issue! The fact is that in `Container` the `clipBehavior` field is specified [the following](https://github.com/flutter/flutter/blame/603104015dd692ea3403755b55d07813d5cf8965/packages/flutter/lib/src/widgets/container.dart#L354):
> /// The clip behavior when [Container.decoration] is not null.
///
/// Defaults to [Clip.none]. Must be [Clip.none] if [decoration] is null.
///
/// If a clip is to be applied, the [Decoration.getClipPath] method
/// for the provided decoration must return a clip path. (This is not
/// supported by all decorations; the default implementation of that
/// method throws an [UnsupportedError].)
final Clip clipBehavior;

Therefore, if we do not use decorations, then the clipper should be in the `Clip.none` position.

You can also use this workaround:
```dart
@override
  Widget build(BuildContext context) {
    return WrapperScene.weather(
      scene: WeatherScene.sunset,
      clip: Clip.none,
    );
  }
```
In this case, you will see protruding elements outside the canvas. Or use the solution from @eunbeek [above](https://github.com/PackRuble/weather_animation/issues/15#issuecomment-2471875109)

---

I'll change this behavior in the next release
