### ISSUE TITLE
D/HostConnection glGetError exceeded non stop log

### ISSUE THREAD

**Issue by Nikzed** [PackRuble/weather_animation#8]
I'm getting non stop ```D/HostConnection( 4523): glGetError exceeded.``` and it's really hard to look through all logs and prints in project cause of this. What's the reason of this this glGetError exceeded log?

**Comment by PackRuble** [comment]
Hello, I saw your question on Stackoverflow and sent you an email:

> [Non stop "glGetError exceeded" in console](https://stackoverflow.com/questions/76447975/non-stop-glgeterror-exceeded-in-console)

Can you share the code so I can reproduce this log? All in all, at a guess, there is no logging in the project and this message is very strange.
